### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/practice#5]
I've included our preliminary unit test results in the paper; what can I do next to be most helpful?

**Comment by jennybc** [comment]
I think, for UseR, we should do some overall descriptive stuff: how many packages? how has that grown over time? descriptive plots (w/ numbers) on the practices we've started to look at … i.e. satisfy people's basic curiosity and give them a feel for the dataset(s) we assembled.

Then basically only tell the testing story. Which may very well venture into the example territory a bit.

Would it be interesting to look at test coverage and/or example coverage in those 50 packages you've looked at by hand?

I think we should look at UseR as a great chance to get feedback and more ideas on what to look for in this data.

I plan to return to this Thursday (got to prepare a practice talk I'm giving tomorrow). I want to do some stuff that takes advantage of our enhanced metadata, i.e. the inclusion of all versions, to say something about behaviour w/r/t updates. Long-term, it would be interesting to answer a question like: if a package doesn't have tests (or whatever) in it initial version, how likely is it that they get added? That is somewhat ambitious for near term because I'd need to look at source over time. If that happened at all, it would be for a small sample of packages.

Other than that, my plan is to make more better descriptive overview plots (that always include numbers and therefore sort of "count" as tables too).

**Comment by Ironholds** [comment]
I think so! Okay: I'll prepare for useR with the following questions:

1. How have package counts increased over time?
2. What about adoption of testthat/roxygen?
3. On testing, what are other ways of doing it?
4. What can all of this tell us about engineering standards, broadly speaking?
5. What other things should be tracking? (list of additional things we plan to track)

If we're treating useR as a distinct feedback thing I'll probably kick off an R Markdown Presentation...thing. for it. Sound good?

**Comment by karthik** [comment]
Sounds like a pretty smashing talk!
I did a Rmd talk last year and it was super easy to share so I highly
recommend it.

If you've got an updated figure for how many packages have tests, would it
be ok for me to cite in my R summit talk? No worries if you don't want me
to share the week before and blow the surprise. Happy to also skip it till
after your useR talk.
- K

**Comment by Ironholds** [comment]
Totally! I'll get you both the raw number and the percentage tomorrow. It's disturbingly low (10-15%)

**Comment by Ironholds** [comment]
@karthik I was wrong, it's 19%! 1248 out of 6465. Of those 1248, 580 are relying on non-standard tests (i.e., a /tests/ directory but neither testthat or RUnit)

**Comment by karthik** [comment]
Great! I'll mention this in a slide and attribute you!
